<?php

declare(strict_types=1);

namespace Seviye\Destek\Tests\Unit\Repository;

use PHPUnit\Framework\TestCase;
use RuntimeException;
use Seviye\Destek\Repository\WpdbSupportTicketRepository;
use Seviye\Destek\Tests\Fakes\FakeConnection;

final class WpdbSupportTicketRepositoryTest extends TestCase
{
    /**
     * The fake connection returns the SAME resultsToReturn for every
     * getResults() call within a single repository method - create()'s
     * final readback (ticket header row + a separate messages row query)
     * can't both succeed against one shared fixture, so the readback
     * throws here - same accepted limitation as
     * plugin/seviye-depo/tests/Unit/Repository/WpdbPurchaseOrderRepositoryTest.php's
     * testCreateInsertsAnAutoGeneratedCodeAndEveryItemRow(). The insert
     * calls that happened before that readback are still fully assertable.
     */
    public function testCreateInsertsTheTicketAndItsOpeningMessage(): void
    {
        $connection = new FakeConnection();
        $connection->nextInsertId = 9;
        $connection->resultsToReturn = [];
        $repository = new WpdbSupportTicketRepository($connection);

        try {
            $repository->create(3, 42, 'Kargo gecikmesi', 'Siparişim hala gelmedi.');
            self::fail('Expected a RuntimeException from the unreadable final find().');
        } catch (RuntimeException) {
            // Expected - see method docblock.
        }

        self::assertCount(2, $connection->inserted);

        [$ticketTable, $ticketData] = $connection->inserted[0];
        self::assertSame('test_scp_support_tickets', $ticketTable);
        self::assertSame(3, $ticketData['branch_id']);
        self::assertSame(42, $ticketData['created_by']);
        self::assertSame('Kargo gecikmesi', $ticketData['subject']);
        self::assertSame('open', $ticketData['status']);

        [$messageTable, $messageData] = $connection->inserted[1];
        self::assertSame('test_scp_support_messages', $messageTable);
        self::assertSame(9, $messageData['ticket_id']);
        self::assertSame(42, $messageData['author_user_id']);
        self::assertSame(0, $messageData['is_staff']);
        self::assertSame('Siparişim hala gelmedi.', $messageData['message']);
    }

    public function testAllForUserReturnsEmptyListWhenNoneMatch(): void
    {
        $connection = new FakeConnection();
        $connection->resultsToReturn = [];
        $repository = new WpdbSupportTicketRepository($connection);

        self::assertSame([], $repository->allForUser(42));
    }

    public function testAllForBranchReturnsEmptyListWhenNoneMatch(): void
    {
        $connection = new FakeConnection();
        $connection->resultsToReturn = [];
        $repository = new WpdbSupportTicketRepository($connection);

        self::assertSame([], $repository->allForBranch(3));
    }

    public function testAllForBranchWithNullScopesToEveryTicket(): void
    {
        $connection = new FakeConnection();
        $connection->resultsToReturn = [];
        $repository = new WpdbSupportTicketRepository($connection);

        $repository->allForBranch(null);

        self::assertStringNotContainsString('WHERE', $connection->queriedSql[0]);
    }

    public function testAddMessageByStaffSetsStatusToAnswered(): void
    {
        $connection = new FakeConnection();
        $connection->nextInsertId = 5;
        $repository = new WpdbSupportTicketRepository($connection);

        $message = $repository->addMessage(9, 7, true, 'Kargo firmasıyla iletişime geçtik.');

        self::assertSame(5, $message->id);
        self::assertTrue($message->isStaff);
        self::assertCount(1, $connection->queries);
        self::assertStringContainsString('status = answered', $connection->queries[0]);
        self::assertStringContainsString('WHERE id = 9', $connection->queries[0]);
    }

    public function testAddMessageByVeliReopensTicketToOpen(): void
    {
        $connection = new FakeConnection();
        $repository = new WpdbSupportTicketRepository($connection);

        $repository->addMessage(9, 42, false, 'Hala gelmedi, ne zaman kargoya verilecek?');

        self::assertStringContainsString('status = open', $connection->queries[0]);
    }

    public function testCloseSetsStatusToClosedWithoutAMessageWhenNoNoteGiven(): void
    {
        $connection = new FakeConnection();
        $repository = new WpdbSupportTicketRepository($connection);

        $repository->close(9, 7, null);

        self::assertSame([], $connection->inserted);
        self::assertCount(1, $connection->queries);
        self::assertStringContainsString('status = closed', $connection->queries[0]);
    }

    public function testCloseInsertsAFinalStaffMessageWhenNoteGiven(): void
    {
        $connection = new FakeConnection();
        $repository = new WpdbSupportTicketRepository($connection);

        $repository->close(9, 7, 'Kargo teslim edildi, konu kapatılıyor.');

        self::assertCount(1, $connection->inserted);
        [, $messageData] = $connection->inserted[0];
        self::assertSame(1, $messageData['is_staff']);
        self::assertSame('Kargo teslim edildi, konu kapatılıyor.', $messageData['message']);

        // addMessage() itself queues an ANSWERED update, close() then
        // overrides it with CLOSED - both queries are expected, in order.
        self::assertCount(2, $connection->queries);
        self::assertStringContainsString('status = answered', $connection->queries[0]);
        self::assertStringContainsString('status = closed', $connection->queries[1]);
    }
}
