<?php

declare(strict_types=1);

namespace Seviye\Depo\Tests\Unit\Repository;

use PHPUnit\Framework\TestCase;
use RuntimeException;
use Seviye\Depo\Repository\WpdbStockCountRepository;
use Seviye\Depo\Tests\Fakes\FakeConnection;

final class WpdbStockCountRepositoryTest extends TestCase
{
    public function testFindItemReturnsNullWhenNoRowMatches(): void
    {
        $connection = new FakeConnection();
        $connection->resultsToReturn = [];
        $repository = new WpdbStockCountRepository($connection);

        self::assertNull($repository->findItem(999));
    }

    public function testFindItemHydratesCountedQuantityAndVariance(): void
    {
        $connection = new FakeConnection();
        $connection->resultsToReturn = [[
            'id' => '4',
            'stock_count_id' => '1',
            'product_id' => '500',
            'expected_quantity' => '20',
            'counted_quantity' => '17',
        ]];
        $repository = new WpdbStockCountRepository($connection);

        $item = $repository->findItem(4);

        self::assertNotNull($item);
        self::assertSame(20, $item->expectedQuantity);
        self::assertSame(17, $item->countedQuantity);
        self::assertSame(-3, $item->variance());
    }

    public function testFindItemHydratesNullCountedQuantityAsUncounted(): void
    {
        $connection = new FakeConnection();
        $connection->resultsToReturn = [[
            'id' => '4',
            'stock_count_id' => '1',
            'product_id' => '500',
            'expected_quantity' => '20',
            'counted_quantity' => null,
        ]];
        $repository = new WpdbStockCountRepository($connection);

        $item = $repository->findItem(4);

        self::assertNotNull($item);
        self::assertNull($item->countedQuantity);
        self::assertNull($item->variance());
    }

    public function testAllReturnsEmptyListWhenNoCountsMatch(): void
    {
        $connection = new FakeConnection();
        $connection->resultsToReturn = [];
        $repository = new WpdbStockCountRepository($connection);

        self::assertSame([], $repository->all());
    }

    public function testSetCountedQuantityRunsAnUpdateQuery(): void
    {
        $connection = new FakeConnection();
        $connection->resultsToReturn = [[
            'id' => '4',
            'stock_count_id' => '1',
            'product_id' => '500',
            'expected_quantity' => '20',
            'counted_quantity' => '17',
        ]];
        $repository = new WpdbStockCountRepository($connection);

        $repository->setCountedQuantity(4, 17);

        self::assertCount(1, $connection->queries);
        self::assertStringContainsString('counted_quantity = 17', $connection->queries[0]);
        self::assertStringContainsString('WHERE id = 4', $connection->queries[0]);
    }

    /**
     * Same FakeConnection limitation as testOpenInsertsTheHeaderAndOneItemPerProductStockLevel()
     * below: with an empty resultsToReturn fixture, complete()'s final
     * find() can't read the header row back, so it throws - the UPDATE
     * that ran before it is still fully assertable.
     */
    public function testCompleteRunsAnUpdateQuerySettingStatusAndCompletedBy(): void
    {
        $connection = new FakeConnection();
        $connection->resultsToReturn = [];
        $repository = new WpdbStockCountRepository($connection);

        try {
            $repository->complete(1, 7);
            self::fail('Expected a RuntimeException from the unreadable final find().');
        } catch (RuntimeException) {
            // Expected - see method docblock.
        }

        self::assertCount(1, $connection->queries);
        self::assertStringContainsString('status = completed', $connection->queries[0]);
        self::assertStringContainsString('completed_by = 7', $connection->queries[0]);
        self::assertStringContainsString('WHERE id = 1', $connection->queries[0]);
    }

    /**
     * Same FakeConnection limitation documented on
     * WpdbPurchaseOrderRepositoryTest::testCreateInsertsAnAutoGeneratedCodeAndEveryItemRow():
     * a single shared resultsToReturn fixture can't serve both the header
     * and the items readback inside open()'s final find(), so the readback
     * throws - the insert calls made before it are still fully assertable.
     */
    public function testOpenInsertsTheHeaderAndOneItemPerProductStockLevel(): void
    {
        $connection = new FakeConnection();
        $connection->resultsToReturn = [];
        $repository = new WpdbStockCountRepository($connection);

        try {
            $repository->open([500 => 20, 501 => 5], 7);
            self::fail('Expected a RuntimeException from the unreadable final find().');
        } catch (RuntimeException) {
            // Expected - see method docblock.
        }

        self::assertCount(3, $connection->inserted);

        [$headerTable, $headerData] = $connection->inserted[0];
        self::assertSame('test_scp_stock_counts', $headerTable);
        self::assertSame('open', $headerData['status']);
        self::assertSame(7, $headerData['started_by']);
        self::assertNull($headerData['completed_by']);

        [$item1Table, $item1Data] = $connection->inserted[1];
        self::assertSame('test_scp_stock_count_items', $item1Table);
        self::assertSame(500, $item1Data['product_id']);
        self::assertSame(20, $item1Data['expected_quantity']);
        self::assertNull($item1Data['counted_quantity']);

        [, $item2Data] = $connection->inserted[2];
        self::assertSame(501, $item2Data['product_id']);
        self::assertSame(5, $item2Data['expected_quantity']);
    }
}
