<?php

declare(strict_types=1);

namespace Seviye\Depo\Tests\Unit\Repository;

use PHPUnit\Framework\TestCase;
use RuntimeException;
use Seviye\Depo\Repository\WpdbPurchaseOrderRepository;
use Seviye\Depo\Support\PurchaseOrderStatusCalculator;
use Seviye\Depo\Tests\Fakes\FakeConnection;

final class WpdbPurchaseOrderRepositoryTest extends TestCase
{
    public function testFindItemReturnsNullWhenNoRowMatches(): void
    {
        $connection = new FakeConnection();
        $connection->resultsToReturn = [];
        $repository = $this->repository($connection);

        self::assertNull($repository->findItem(999));
    }

    public function testFindItemHydratesTheRow(): void
    {
        $connection = new FakeConnection();
        $connection->resultsToReturn = [[
            'id' => '4',
            'purchase_order_id' => '10',
            'product_id' => '500',
            'quantity_ordered' => '20',
            'quantity_received' => '12',
            'unit_cost' => '45.50',
        ]];
        $repository = $this->repository($connection);

        $item = $repository->findItem(4);

        self::assertNotNull($item);
        self::assertSame(4, $item->id);
        self::assertSame(20, $item->quantityOrdered);
        self::assertSame(12, $item->quantityReceived);
        self::assertSame(45.50, $item->unitCost);
    }

    public function testAllReturnsEmptyListWhenNoOrdersMatch(): void
    {
        $connection = new FakeConnection();
        $connection->resultsToReturn = [];
        $repository = $this->repository($connection);

        self::assertSame([], $repository->all());
    }

    public function testSendRunsAnUpdateQuerySettingStatusToSent(): void
    {
        $connection = new FakeConnection();
        $repository = $this->repository($connection);

        $repository->send(4);

        self::assertCount(1, $connection->queries);
        self::assertStringContainsString('status = sent', $connection->queries[0]);
        self::assertStringContainsString('WHERE id = 4', $connection->queries[0]);
    }

    public function testCancelRunsAnUpdateQuerySettingStatusToCancelled(): void
    {
        $connection = new FakeConnection();
        $repository = $this->repository($connection);

        $repository->cancel(4);

        self::assertCount(1, $connection->queries);
        self::assertStringContainsString('status = cancelled', $connection->queries[0]);
    }

    /**
     * The fake connection returns the SAME resultsToReturn for every
     * getResults() call within a single repository method - create()'s
     * final readback (header row + a separate items row query) can't both
     * succeed against one shared fixture, so the readback throws here.
     * The insert calls that happened before that readback are still fully
     * assertable, which is what this test actually verifies.
     */
    public function testCreateInsertsAnAutoGeneratedCodeAndEveryItemRow(): void
    {
        $connection = new FakeConnection();
        $connection->resultsToReturn = [];
        $repository = $this->repository($connection);

        try {
            $repository->create(3, '2026-08-10', 'Yıllık forma siparişi', 7, [
                ['product_id' => 500, 'quantity_ordered' => 20, 'unit_cost' => 45.5],
                ['product_id' => 501, 'quantity_ordered' => 5, 'unit_cost' => null],
            ]);
            self::fail('Expected a RuntimeException from the unreadable final find().');
        } catch (RuntimeException) {
            // Expected - see method docblock.
        }

        self::assertCount(3, $connection->inserted);

        [$headerTable, $headerData] = $connection->inserted[0];
        self::assertSame('test_scp_purchase_orders', $headerTable);
        self::assertSame(3, $headerData['supplier_id']);
        self::assertSame('draft', $headerData['status']);
        self::assertStringStartsWith('PO-', $headerData['code']);

        [$item1Table, $item1Data] = $connection->inserted[1];
        self::assertSame('test_scp_purchase_order_items', $item1Table);
        self::assertSame(500, $item1Data['product_id']);
        self::assertSame(20, $item1Data['quantity_ordered']);
        self::assertSame(45.5, $item1Data['unit_cost']);

        [, $item2Data] = $connection->inserted[2];
        self::assertSame(501, $item2Data['product_id']);
        self::assertNull($item2Data['unit_cost']);
    }

    private function repository(FakeConnection $connection): WpdbPurchaseOrderRepository
    {
        return new WpdbPurchaseOrderRepository($connection, new PurchaseOrderStatusCalculator());
    }
}
