<?php

declare(strict_types=1);

namespace Seviye\SubeSiparis\Tests\Unit\Repository;

use PHPUnit\Framework\TestCase;
use RuntimeException;
use Seviye\SubeSiparis\Repository\WpdbBranchOrderQuotaRepository;
use Seviye\SubeSiparis\Tests\Fakes\FakeConnection;

final class WpdbBranchOrderQuotaRepositoryTest extends TestCase
{
    public function testFindReturnsNullWhenNoRowMatches(): void
    {
        $connection = new FakeConnection();
        $connection->resultsToReturn = [];
        $repository = new WpdbBranchOrderQuotaRepository($connection);

        self::assertNull($repository->find(3, 500));
    }

    public function testFindHydratesTheRow(): void
    {
        $connection = new FakeConnection();
        $connection->resultsToReturn = [[
            'id' => '9',
            'branch_id' => '3',
            'product_id' => '500',
            'free_quantity' => '100',
            'created_at' => '2026-08-01 10:00:00',
            'updated_at' => '2026-08-01 10:00:00',
        ]];
        $repository = new WpdbBranchOrderQuotaRepository($connection);

        $quota = $repository->find(3, 500);

        self::assertNotNull($quota);
        self::assertSame(9, $quota->id);
        self::assertSame(100, $quota->freeQuantity);
    }

    public function testUpsertRunsAnInsertOnDuplicateKeyUpdateQuery(): void
    {
        $connection = new FakeConnection();
        $connection->resultsToReturn = [];

        $repository = new WpdbBranchOrderQuotaRepository($connection);

        try {
            $repository->upsert(3, 500, 100);
            self::fail('Expected a RuntimeException from the unreadable final find().');
        } catch (RuntimeException) {
            // Same "fake connection returns a fixed result" limitation as
            // WpdbPurchaseOrderRepositoryTest::testCreateInsertsAnAutoGeneratedCodeAndEveryItemRow() -
            // the query itself is still fully assertable below.
        }

        self::assertCount(1, $connection->queries);
        self::assertStringContainsString('ON DUPLICATE KEY UPDATE', $connection->queries[0]);
        self::assertStringContainsString('INSERT INTO test_scp_branch_order_quotas', $connection->queries[0]);
    }

    public function testAllReturnsEmptyListWhenNoQuotasMatch(): void
    {
        $connection = new FakeConnection();
        $connection->resultsToReturn = [];
        $repository = new WpdbBranchOrderQuotaRepository($connection);

        self::assertSame([], $repository->all());
    }

    public function testDeleteRunsADeleteQuery(): void
    {
        $connection = new FakeConnection();
        $repository = new WpdbBranchOrderQuotaRepository($connection);

        $repository->delete(9);

        self::assertCount(1, $connection->queries);
        self::assertStringContainsString('DELETE FROM test_scp_branch_order_quotas', $connection->queries[0]);
        self::assertStringContainsString('WHERE id = 9', $connection->queries[0]);
    }
}
